name: 'ebp #1'
favicon: null
layout_spectrum: 0.8676363984122872
typography_spectrum: 0.5263772034086287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef2d8'
    - '#900031'
    - '#191919'
    - '#b49f9b'
    - '#8f726e'
  brandStrength: 0.5625
  lightness: 0.8268493874929845
  saturation: 0.1598353609442711
  rhythmicContrast: 0.7921157686505467
purpose: []
